language: c
dist: trusty
compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libsdl2-dev libgl1-mesa-dev libsdl2-ttf-dev libportmidi-dev libfftw3-dev libsamplerate0-dev libdrm-dev freeglut3-dev libutfcpp-dev libglew-dev
    - git clone --quiet --depth=100 "https://github.com/EddieRingle/portaudio" ~/builds/portaudio
      && pushd ~/builds/portaudio
      && ./configure
      && make CC="$CC"
      && sudo make install
      && popd;

script: make CC="$CC"


