language: c
dist: trusty
compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install cmake qtdeclarative5-dev qtdeclarative5-quicklayouts-plugin qt5-default libsdl2-dev

install:
    - mkdir build
      && cd build
      && cmake ..
      && make CC="$CC"
